import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import AppShell from '../components/layout/AppShell'
import ProjectMap from '../components/map/ProjectMap'
import AnalyticsPanel from '../components/analytics/AnalyticsPanel'
import { api } from '../services/api'

function SiteList({ sites, selectedSiteId, onSelect }) {
  return <div className="site-list">{sites.map((site, index) => <button key={site.id} className={site.id === selectedSiteId ? 'site-list-item selected' : 'site-list-item'} onClick={() => onSelect(site.id)}><span className="site-number">{String(index + 1).padStart(2, '0')}</span><span className="site-list-copy"><strong>{site.name}</strong><small>{site.analytics ? `${site.analytics.value.toLocaleString(undefined, { maximumFractionDigits: 0 })} tonnes CO2 · ${site.analytics.year}` : 'No intersecting data'}</small></span><span>→</span></button>)}</div>
}

export default function ProjectDashboard() {
  const { projectId } = useParams(); const [dashboard, setDashboard] = useState(null); const [selectedSiteId, setSelectedSiteId] = useState(null); const [drawing, setDrawing] = useState(false); const [drawnGeometry, setDrawnGeometry] = useState(null); const [siteForm, setSiteForm] = useState({ name: '', description: '' }); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState('')
  async function loadDashboard() { setError(''); try { setDashboard(await api.dashboard(projectId)) } catch (requestError) { setError(requestError.message) } }
  useEffect(() => { loadDashboard() }, [projectId])
  const selectedSite = dashboard?.sites.find((site) => site.id === selectedSiteId)
  async function createSite(event) { event.preventDefault(); if (!drawnGeometry) return; setIsSaving(true); try { const created = await api.createSite(projectId, { name: siteForm.name, description: siteForm.description || null, geometry: drawnGeometry }); setDashboard((current) => ({ ...current, sites: [...current.sites, { id: created.id, name: created.name, geometry: created.geometry, analytics: null }] })); setSelectedSiteId(created.id); setDrawnGeometry(null); setSiteForm({ name: '', description: '' }) } catch (requestError) { setError(requestError.message) } finally { setIsSaving(false) } }
  if (!dashboard) return <AppShell><div className="center-state"><span className="spinner" /> {error || 'Loading project intelligence...'}</div></AppShell>
  return <AppShell><header className="dashboard-header"><div><Link to="/projects" className="back-link">← All projects</Link><span className="eyebrow">Project dashboard</span><h1>{dashboard.project.name}</h1><p>{dashboard.project.description || 'A living view of your project sites and environmental signal.'}</p></div><button className={drawing ? 'secondary-button drawing-active' : 'primary-button'} onClick={() => setDrawing((current) => !current)}>{drawing ? 'Finish drawing' : '＋ Add site'}</button></header>{error && <div className="alert error-alert">{error}<button onClick={loadDashboard}>Retry</button></div>}<div className="dashboard-layout"><section className="map-section"><div className="map-toolbar"><div><span className="eyebrow">Site atlas</span><strong>{dashboard.sites.length} {dashboard.sites.length === 1 ? 'site' : 'sites'} mapped</strong></div>{drawing && <span className="draw-instruction"><span className="status-dot" /> Click points on the map to outline a polygon</span>}</div><ProjectMap sites={dashboard.sites} selectedSiteId={selectedSiteId} onSelectSite={setSelectedSiteId} drawing={drawing} onDrawComplete={(geometry) => { setDrawing(false); setDrawnGeometry(geometry) }} /></section><aside className="sites-rail"><div className="rail-heading"><div><span className="eyebrow">Sites</span><h2>Project footprint</h2></div><span className="count-badge">{dashboard.sites.length}</span></div>{dashboard.sites.length ? <SiteList sites={dashboard.sites} selectedSiteId={selectedSiteId} onSelect={setSelectedSiteId} /> : <div className="rail-empty"><div className="empty-icon">⌁</div><strong>No sites mapped</strong><p>Use Add site to draw the first polygon on your project map.</p></div>}<div className="rail-note"><span>↗</span><p>Analytics are calculated from the EDGAR India CO2 grid at the moment you select a site.</p></div></aside></div>{drawnGeometry && <div className="modal-backdrop"><form className="modal-card" onSubmit={createSite}><div className="modal-heading"><div><span className="eyebrow">New polygon captured</span><h2>Name this site</h2></div><button type="button" className="close-button" onClick={() => setDrawnGeometry(null)}>×</button></div><label>Site name<input required maxLength={200} value={siteForm.name} onChange={(event) => setSiteForm({ ...siteForm, name: event.target.value })} placeholder="e.g. Mulshi watershed" /></label><label>Description <span className="optional">Optional</span><textarea maxLength={5000} rows="4" value={siteForm.description} onChange={(event) => setSiteForm({ ...siteForm, description: event.target.value })} placeholder="Add context for this site" /></label><button className="primary-button full-width" disabled={isSaving}>{isSaving ? 'Saving site...' : 'Save site'}<span>→</span></button></form></div>}{selectedSite && <div className="analytics-overlay"><AnalyticsPanel site={selectedSite} onClose={() => setSelectedSiteId(null)} /></div>}</AppShell>
}
