import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import AppShell from '../components/layout/AppShell'
import { api } from '../services/api'

function ProjectCard({ project, onOpen, onDelete }) {
  return <article className="project-card"><div className="project-card-top"><div className="project-icon">{project.name.slice(0, 1).toUpperCase()}</div><button className="quiet-button danger" onClick={() => onDelete(project)} aria-label={`Delete ${project.name}`}>Delete</button></div><button className="project-card-body" onClick={() => onOpen(project.id)}><h3>{project.name}</h3><p>{project.description || 'No description added yet.'}</p><div className="project-card-meta"><span>Project {String(project.id).padStart(3, '0')}</span><span>{new Date(project.created_at).toLocaleDateString(undefined, { month: 'short', year: 'numeric' })}</span></div></button><div className="project-card-arrow">↗</div></article>
}

export default function Projects() {
  const navigate = useNavigate(); const [projects, setProjects] = useState([]); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState(''); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ name: '', description: '' }); const [isSaving, setIsSaving] = useState(false)
  async function loadProjects() { setIsLoading(true); setError(''); try { setProjects(await api.projects()) } catch (requestError) { setError(requestError.message) } finally { setIsLoading(false) } }
  useEffect(() => { loadProjects() }, [])
  async function createProject(event) { event.preventDefault(); setIsSaving(true); try { const project = await api.createProject({ name: form.name, description: form.description || null }); setProjects((current) => [...current, project]); setForm({ name: '', description: '' }); setShowForm(false); navigate(`/projects/${project.id}`) } catch (requestError) { setError(requestError.message) } finally { setIsSaving(false) } }
  async function deleteProject(project) { if (!window.confirm(`Delete ${project.name}? This also removes its sites.`)) return; try { await api.deleteProject(project.id); setProjects((current) => current.filter((item) => item.id !== project.id)) } catch (requestError) { setError(requestError.message) } }
  return <AppShell><header className="page-header"><div><span className="eyebrow">Workspace / Projects</span><h1>Your projects</h1><p>Monitor the places where your climate work takes root.</p></div><button className="primary-button" onClick={() => setShowForm(true)}>＋ New project</button></header>{error && <div className="alert error-alert">{error}<button onClick={loadProjects}>Retry</button></div>}{showForm && <div className="modal-backdrop"><form className="modal-card" onSubmit={createProject}><div className="modal-heading"><div><span className="eyebrow">New workspace</span><h2>Create a project</h2></div><button type="button" className="close-button" onClick={() => setShowForm(false)}>×</button></div><label>Project name<input required maxLength={200} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="e.g. Western Ghats restoration" /></label><label>Description <span className="optional">Optional</span><textarea maxLength={5000} rows="4" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="What is this project working toward?" /></label><button className="primary-button full-width" disabled={isSaving}>{isSaving ? 'Creating...' : 'Create project'}<span>→</span></button></form></div>}<section className="section-heading"><div><span className="eyebrow">All workspaces</span><h2>{projects.length} {projects.length === 1 ? 'project' : 'projects'}</h2></div></section>{isLoading ? <div className="loading-row"><span className="spinner" /> Loading projects...</div> : projects.length === 0 ? <div className="empty-state"><div className="empty-icon">＋</div><h3>No projects yet</h3><p>Create your first project to start mapping sites and environmental impact.</p><button className="secondary-button" onClick={() => setShowForm(true)}>Create first project</button></div> : <div className="project-grid">{projects.map((project) => <ProjectCard key={project.id} project={project} onOpen={(id) => navigate(`/projects/${id}`)} onDelete={deleteProject} />)}<button className="new-project-tile" onClick={() => setShowForm(true)}><span>＋</span><strong>Add another project</strong><small>Keep your work organized</small></button></div>}</AppShell>
}
