import { useEffect, useState } from 'react'
import { Line } from 'react-chartjs-2'
import { CategoryScale, Chart as ChartJS, Filler, Legend, LinearScale, LineElement, PointElement, Tooltip } from 'chart.js'
import { api } from '../../services/api'

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Tooltip, Legend, Filler)

export default function AnalyticsPanel({ site, onClose }) {
  const [analytics, setAnalytics] = useState(site.analytics); const [timeseries, setTimeseries] = useState(null); const [dataset, setDataset] = useState(null); const [isLoading, setIsLoading] = useState(!site.analytics); const [error, setError] = useState('')
  useEffect(() => { let active = true; setIsLoading(true); Promise.all([api.siteAnalytics(site.id), api.siteTimeseries(site.id), api.datasets()]).then(([metric, series, metadata]) => { if (!active) return; setAnalytics(metric); setTimeseries(series); setDataset(metadata) }).catch((requestError) => { if (active) setError(requestError.message) }).finally(() => active && setIsLoading(false)); return () => { active = false } }, [site.id])
  const chartData = timeseries ? { labels: timeseries.data.map((point) => point.year), datasets: [{ label: `${timeseries.metric.toUpperCase()} (${timeseries.unit})`, data: timeseries.data.map((point) => point.value), borderColor: '#d9833b', backgroundColor: 'rgba(217, 131, 59, .12)', fill: true, tension: .35, pointRadius: 5, pointBackgroundColor: '#fff', pointBorderWidth: 2 }] } : null
  return <aside className="analytics-panel"><div className="panel-heading"><div><span className="eyebrow">Site intelligence</span><h2>{site.name}</h2></div><button className="close-button" onClick={onClose} aria-label="Close site details">×</button></div>{isLoading ? <div className="loading-row"><span className="spinner" /> Computing site impact...</div> : error ? <div className="empty-state compact"><div className="empty-icon">!</div><h3>No environmental data</h3><p>{error}</p></div> : <><div className="metric-hero"><span className="metric-label">Annual CO2 intersect</span><strong>{analytics.value.toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong><div><span>{analytics.unit}</span><span className="metric-year">{analytics.year}</span></div></div><div className="metric-row"><div><span className="eyebrow">Grid cells</span><strong>{analytics.grid_cells}</strong></div><div><span className="eyebrow">Metric</span><strong>{analytics.metric.toUpperCase()}</strong></div></div>{chartData && <section className="chart-section"><div className="chart-title"><div><span className="eyebrow">Historical signal</span><h3>Emissions over time</h3></div><span className="chart-range">{timeseries.available_years.join(' · ')}</span></div><div className="chart-wrap"><Line data={chartData} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false }, tooltip: { callbacks: { label: (context) => `${context.parsed.y.toLocaleString()} tonnes` } } }, scales: { x: { grid: { display: false }, ticks: { color: '#78908b' } }, y: { grid: { color: '#e5ece6' }, ticks: { color: '#78908b' } } } }} /></div><p className="chart-note">Currently available dataset: {timeseries.available_years.length === 1 ? timeseries.available_years[0] : `${timeseries.available_years[0]}–${timeseries.available_years.at(-1)}`}</p></section>} {dataset && <section className="dataset-section"><div className="section-heading-inline"><span className="eyebrow">Data source</span><span className="source-badge">Verified</span></div><h3>{dataset.dataset_name}</h3><p>{dataset.description}</p><dl><div><dt>Source</dt><dd>{dataset.source}</dd></div><div><dt>Resolution</dt><dd>{dataset.geographic_resolution}</dd></div><div><dt>Coverage</dt><dd>{dataset.years.join(', ')}</dd></div></dl></section>}</>}</aside>
}
